trigger:
  branches:
    include:
      - "main"

schedules:
- cron: '0 0 * * *'
  displayName: Daily midnight run
  branches:
    include:
    - main
  always: true

pr: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: deploy

    jobs:
    - deployment: 'deploy_to_dedi_prd'
      environment:
        name: platform-dedi-prd
        resourceType: VirtualMachine
      variables:
        - group: Cloudflare

      strategy:
        runOnce:
          deploy:
            steps:

            - checkout: self
              clean: true

            - task: PowerShell@2
              inputs:
                targetType: 'inline'
                script: |
                  Write-Host "Running on $($env:COMPUTERNAME)"

            - task: PowerShell@2
              inputs:
                targetType: 'filePath'
                filePath: 'rotate-iis-certificates.ps1'
                arguments: '-cloudflareApiKey $(API-KEY)'