trigger:
  branches:
    include:
      - "main"

pr: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: deploy

    jobs:
    - deployment: 'deploy_to_dedi_prd'
      environment:
        name: platform-dedi-prd
        resourceType: VirtualMachine

      strategy:
        runOnce:
          deploy:
            steps:

            - checkout: self
              clean: true

            - task: PowerShell@2
              inputs:
                targetType: 'inline'
                pwsh: true
                script: |
                  Write-Host "Running on $($env:COMPUTERNAME)"

            - task: PowerShell@2
              inputs:
                targetType: 'filePath'
                filePath: 'rotate-iis-certificates.ps1'
                pwsh: true